apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:9-alpine
        env:
        - name: POSTGRES_USER
          value: wallet
        - name: POSTGRES_PASSWORD
          value: wallet
        ports:
        - containerPort: 5432
