---
apiVersion: v1
kind: Service
metadata:
  name: router
  labels:
    app: router
spec:
  ports:
  - port: 8080
    name: router
  selector:
    app: router
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: router-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: router
    spec:
      containers:
      - name: router
        image: alexec/router:latest
        imagePullPolicy: Always
        env:
          - name: JAVA_OPTS
            value: -Xmx256m
        ports:
        - containerPort: 9000
        resources:
          limits:
            memory: 256Mi
        readinessProbe:
          httpGet:
            path: /api/wallet
            port: 8080
            httpHeaders:
            - name: Host
              value: localhost
            - name: Authorization
              value: "Basic cm91dGVyOnJvdXRlcg=="
          initialDelaySeconds: 15
          periodSeconds: 15
        livenessProbe:
          httpGet:
            path: /api/wallet
            port: 8080
            httpHeaders:
            - name: Host
              value: localhost
            - name: Authorization
              value: "Basic cm91dGVyOnJvdXRlcg=="
          initialDelaySeconds: 15
          periodSeconds: 15
