---
apiVersion: v1
kind: Service
metadata:
  name: statedb
  labels:
    app: statedb
spec:
  ports:
  - port: 27017
    name: statedb
  clusterIP: None
  selector:
    app: statedb
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: statedb
spec:
  serviceName: statedb
  replicas: 1
  template:
    metadata:
      labels:
        app: statedb
    spec:
      containers:
      - name: mongo
        image: mongo:3
        ports:
        - containerPort: 27017
