---
apiVersion: v1
kind: Service
metadata:
  name: walletdb
  labels:
    app: walletdb
spec:
  ports:
  - port: 5432
    name: walletdb
  clusterIP: None
  selector:
    app: walletdb
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: walletdb
spec:
  serviceName: walletdb
  replicas: 1
  template:
    metadata:
      labels:
        app: walletdb
    spec:
      containers:
      - name: postgres
        image: postgres:9-alpine
        env:
        - name: POSTGRES_USER
          value: wallet
        - name: POSTGRES_PASSWORD
          value: wallet
        ports:
        - containerPort: 5432
