version: 2
jobs:
  build:
    working_directory: ~/work
    docker:
      - image: "circleci/openjdk:8"
    steps:
      - checkout
      - run: curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
      - run: chmod +x kubectl
      - run: sudo apt-get -y install gnupg
      - run: echo $GPG_KEY | gpg -d --passphrase-fd 0  --batch --yes kubeconfig.gpg > kubeconfig
      - run: envsubst < manifests/$COMPONENT.yml > tmp
      - run: mv tmp manifests/$COMPONENT.yml
      - run: git diff manifests/$COMPONENT.yml
      - run:
          environment:
            KUBECONFIG: kubeconfig
          command: ./kubectl apply -f manifests/$COMPONENT.yml
      - run:
          environment:
            KUBECONFIG: kubeconfig
          command: ./kubectl exec $(./kubectl get pods -o name -l app=web|cut -c 6-) -- nginx -s reload
      - run: "curl -f -u $CIRCLE_TOKEN: -X POST https://circleci.com/api/v1.1/project/github/phoebus-games/smoke/tree/master"
