---
apiVersion: v1
kind: Service
metadata:
  name: router
  labels:
    app: router
spec:
  ports:
  - port: 9000
    name: router
  selector:
    app: router
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: router-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: router
    spec:
      containers:
      - name: router
        image: alexec/router:$VERSION
        env:
          - name: JAVA_OPTS
            value: -Xmx256m
          - name: APPLICATION_SECRET
            value: XXXXXX
        ports:
        - containerPort: 9000
        resources:
          limits:
            memory: 256Mi
