---
- name: Create Wallet
  command: createdb wallet
  become: true
  become_user: postgres

- name: Set Wallet Password
  command: psql -c "ALTER USER wallet WITH PASSWORD 'wallet';"
  become: true
  become_user: postgres
